DROP DATABASE IF EXISTS jenkins;
CREATE DATABASE jenkins; 
USE jenkins;

CREATE TABLE IF NOT EXISTS build_history (
	build_history_id INT(11) NOT NULL AUTO_INCREMENT,
	BUILD_ID     VARCHAR(100) DEFAULT NULL,
	BUILD_NUMBER VARCHAR(100) DEFAULT NULL,
	BUILD_URL    VARCHAR(400) DEFAULT NULL,
	BUILD_TAG    VARCHAR(100) DEFAULT NULL,
	DOCKER_REPO  VARCHAR(100) DEFAULT NULL,
	DOCKER_TAG   VARCHAR(100) DEFAULT NULL,
	GIT_BRANCH   VARCHAR(100) DEFAULT NULL,
	GIT_COMMIT   VARCHAR(100) DEFAULT NULL,
	GIT_URL      VARCHAR(400) DEFAULT NULL,
	JOB_NAME     VARCHAR(200) DEFAULT NULL,
	PRIMARY KEY (build_history_id)
) ENGINE=InnoDB
